[package]
name = "dirwatch"
version = "0.1.0"
edition = "2021"

[dependencies]
readln = { git = "https://github.com/Stuff7/readlnrs", branch = "bytes" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
